#!/bin/sh

# Aliases file

## basic
alias ls='lsd $LSD_OPTIONS'
alias l='lsd $LSD_OPTIONS -l'
alias ll='lsd $LSD_OPTIONS -lA'
alias lspp='ls++ --potsf'
alias cat='bat'
alias pping='prettyping'
alias yay='yay $PACMAN_OPTIONS'
alias paru='paru $PACMAN_OPTIONS'
alias pacman='pacman $PACMAN_OPTIONS'
alias update='yay -Syu'
alias sshinsecure='ssh -oKexAlgorithms=+diffie-hellman-group1-sha1'

alias rg='rg -p'

## fs-listers

alias appimages='ranger $HOME/Downloads/appimage'

### helpers
alias tstamp='date +%Y%m%d%H%M%S'
alias psearch='ps -ef | sed 1d|fzf -m|awk '{print $2}''

### git sync for dotfiles and todo
alias dotfiles='/usr/bin/git --git-dir=$DOTFILES --work-tree=$HOME'
alias dotfiles-commit='dotfiles add -u && dotfiles commit -m "Quick Commit $(date +%Y-%m-%d.%H:%M:%S)"'
alias dotfiles-push='dotfiles push -u origin master'
alias tasks='nvim ~/todo.md'
alias todo='/usr/bin/git --git-dir=$XDG_CONFIG_HOME/todo/ --work-tree=$HOME'
alias update-todo='todo add $HOME/todo.md && todo commit -m "Update $(date +%Y-%m-%d.%H:%M:%S)" && todo push -u origin'

### manage wine
alias wineprocs='ps auxwww | grep -iE "wine|\.exe" | grep -v grep'
alias wineprocids='wineprocs | tr -s " " | cut -d" " -f 2'
alias winekill='wineprocids | xargs kill -9 2>&1 > /dev/null || echo "No wine processes found"'
alias wineterm='wineprocids | xargs kill -15 2>&1 > /dev/null || echo "No wine processes found"'

### youtube
alias yt='youtube-dl --add-metadata -ic'
alias yta='youtube-dl --add-metadata -icc'
alias ytv='youtube-viewer'

### spotify
alias spotrec='spotrec -t -o $XDG_MUSIC_DIR/SpotRec'

