#!/bin/sh

# Aliases file

## basic
alias ls='lsd $LSD_OPTIONS'
alias l='lsd $LSD_OPTIONS -l'
alias ll='lsd $LSD_OPTIONS -lA'
alias lspp='ls++ --potsf'
alias cat='bat'
alias yay='yay $PACMAN_OPTIONS'
alias paru='paru $PACMAN_OPTIONS'
alias pacman='pacman $PACMAN_OPTIONS'
alias sshinsecure='ssh -oKexAlgorithms=+diffie-hellman-group1-sha1'

## fixes
alias tmux='tmux -f "$TMUX_CONFIG_HOME/tmux.conf"'

### helpers
alias tstamp='date +%Y%m%d%H%M%S'

### git sync for dotfiles and todo
alias dotfiles='/usr/bin/git --git-dir=$DOTFILES --work-tree=$HOME'
alias dotfiles-commit='config add -u && config commit -m "Quick Commit $(date +%Y-%m-%d.%H:%M:%S)"'
alias dotfiles-push='config push -u origin master'
alias tasks='nvim ~/todo.md'
alias todo='/usr/bin/git --git-dir=$XDG_CONFIG_HOME/todo/ --work-tree=$HOME'
alias update-todo='todo add $HOME/todo.md && todo commit -m "Update $(date +%Y-%m-%d.%H:%M:%S)" && todo push -u origin'

### manage wine
alias wineprocs='ps auxwww | egrep -iE "wine|\.exe" | grep -v grep'
alias wineprocids='wineprocs | tr -s " " | cut -d" " -f 2'
alias winekill='wineprocids | xargs kill -9 2>&1 > /dev/null || echo "No wine processes found"'
alias wineterm='wineprocids | xargs kill -15 2>&1 > /dev/null || echo "No wine processes found"'

### youtube
alias yt='youtube-dl --add-metadata -ic'
alias yta='youtube-dl --add-metadata -icc'
alias ytv='youtube-viewer'

### spotify
alias spotrec='spotrec -t -o $XDG_MUSIC_DIR/SpotRec'

### work
alias tssh='/usr/bin/ssh-keygen -R localhost && /usr/bin/ssh -oStrictHostKeyChecking=no kace_support@localhost'
alias trssh='/usr/bin/ssh-keygen -R localhost && /usr/bin/ssh -oStrictHostKeyChecking=no root@localhost'
alias tsssh='/usr/bin/ssh-keygen -R localhost && /usr/bin/ssh -oStrictHostKeyChecking=no kace_support@localhost -t -- screen -R'
alias trsssh='/usr/bin/ssh-keygen -R localhost && /usr/bin/ssh -oStrictHostKeyChecking=no root@localhost -t -- screen -R'
alias readdocs='ranger $HOME/Documents/Text/Manuals'
# alias iamgroot='cat $HOME/Documents/notes/kace/KnowHow/iamgroot.txt'
alias iamgroot='cat $XDG_DOCUMENTS_DIR/notes/kace/KnowHow/iamgroot.md'
# alias iamgroot='lookatme $XDG_DOCUMENTS_DIR/notes/kace/KnowHow/iamgroot.md'

### game streaming
alias streamlink='streamlink -p mpv --twitch-disable-ads'
alias jorbs='streamlink https://twitch.tv/joinrbs best'

### sumneko
alias luamake='/home/thorsten/.config/cache/nvim/nlua/sumneko_lua/lua-language-server/3rd/luamake/luamake'
